//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campos
    {
        public string chaveNfeCte { get; set; }
        public string cnpjEmitente { get; set; }
        public string CnpjDestinatario { get; set; }
        public string total { get; set; }
        public string infAdic { get; set; }
        public byte[] Xml { get; set; }
    }
}
